In [1]:
import pandas as pd
paths = [
    "/kaggle/input/data-annot-part-1/checkpoint_10000.csv",
    "/kaggle/input/data-annot-part-2/checkpoint_10000.csv",
    "/kaggle/input/data-annot-part-3/annotated_dataset_3.csv",
    "/kaggle/input/data-annot-part-4/annotated_dataset_4.csv",
    "/kaggle/input/data-annot-part-5/annotated_dataset_5.csv"
]

df = pd.concat([pd.read_csv(p) for p in paths], ignore_index = True)
df.shape

(45461, 2)

In [2]:
df.isna().sum()

text       0
labels    10
dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45461 entries, 0 to 45460
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    45461 non-null  object
 1   labels  45451 non-null  object
dtypes: object(2)
memory usage: 710.5+ KB

In [4]:
df[df["labels"].isna()]

                                                    text labels
3892   প্রধান উপদেষ্টা অধ্যাপক মুহাম্মদ ইউনূসের আগামী...    NaN
12126  সুপ্রিম কোর্ট প্রাঙ্গণে বেসামরিক বিমান পরিবহন ...    NaN
13562  বাংলাদেশ সেনাবাহিনীর ইঞ্জিনিয়ার্স, ইএমই এবং এ...    NaN
21472  সাবেক নৌবাহিনী প্রধান ভাইস অ্যাডমিরাল সরওয়ার জ...    NaN
21497  বাংলাদেশ নৌবাহিনীর সাবেক প্রধান ভাইস অ্যাডমিরা...    NaN
21995  গ্রেটওয়াল, চারু সিরামিক ও বেঙ্গল এজেন্সিস'র ব্...    NaN
22958  বাংলাদেশ বিমান বাহিনীর ২০২৪ সালের শ্রেষ্ঠ বিমা...    NaN
23340  মেক্সিকোতে নিযুক্ত বাংলাদেশের রাষ্ট্রদূত মুশফি...    NaN
24738  দেশের শীর্ষস্থানীয় গণমাধ্যমগুলোর অনলাইন ও ডিজ...    NaN
39721  হাকিমপুরী জর্দার ব্যবসায়ী মো. কাউছ মিয়া (৯৪) আ...    NaN

In [5]:
df = df.dropna()

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45451 entries, 0 to 45460
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    45451 non-null  object
 1   labels  45451 non-null  object
dtypes: object(2)
memory usage: 1.0+ MB

In [7]:
df.isna().sum()

text      0
labels    0
dtype: int64

In [8]:
labels = [
    'রাজনীতি',
    'সরকারি-নীতি',
    'নির্বাচন',
    'আইন-শৃঙ্খলা',
    'আইন',
    'দুর্নীতি',
    'আন্তর্জাতিক',
    'অর্থনীতি',
    'বাণিজ্য',
    'ব্যাংকিং',
    'সমাজ',
    'সংস্কৃতি',
    'ধর্ম',
    'শিক্ষা',
    'জীবনধারা',
    'ফ্যাশন',
    'প্রযুক্তি',
    'স্বাস্থ্য',
    'বিজ্ঞান',
    'ক্রীড়া',
    'বিনোদন',
    'সেলিব্রিটি',
    'অপরাধ',
    'দুর্ঘটনা',
    'দুর্যোগ',
    'পরিবেশ',
    'কৃষি',
    'পর্যটন',
    'যানজট/ট্রাফিক',
    'আবাসন',
    'বিশেষ প্রতিবেদন',
    'শেয়ারবাজার',
    'শিল্প-কারখানা',
    'উৎসব',
    'ক্রিকেট',
    'ফুটবল',
    'অন্যান্য-খেলা',
    'সংসদ',
    'বি এন পি',
    'আওমীলীগ',
    'জামায়াত',
    'ঢাকা',
    'চটগ্রাম',
    'জেলা সংবাদ',
    'আবহাওয়া',
    'কূটনীতি',
    'অপহরণ',
    'হত্যা',
    'রোগ-বিস্তার',
    'আইন'
]

In [9]:
allowed = set(labels)

In [10]:
def find_illegal_str(lbl_str):
    if pd.isna(lbl_str):
        return True
    row_labels = [x.strip() for x in lbl_str.split(",")]
    for lbl in row_labels:
        if lbl not in allowed:
            return True
    return False

bad_rows = df[df["labels"].apply(find_illegal_str)]

In [11]:
bad_rows

,text,labels
6,"তথ্য ও সম্প্রচার উপদেষ্টা নাহিদ ইসলাম বলেছেন, ...","রাজনীতি, আইন-শৃঙ্খলা, অপরাধ, সমাজ, অন্যান্য-খে..."
16,সেনাবাহিনীর আর্টিলারি রেজিমেন্ট এবং আর্মি মেডি...,"সামরিক, সমাজ, অন্যান্য-খেলা"
48,"বৈষম্যবিরোধী আন্দোলনে হামলা, গুলি ও ককটেল বিস্...","রাজনীতি, আইন-শৃঙ্খলা, অপরাধ, সমাজ, শিক্ষা, চট্..."
75,ঢাকা দক্ষিণ সিটি করপোরেশনের সাবেক মেয়র ব্যারিস...,"রাজনীতি, দুর্নীতি, আইন, ঢাকা, সংসদ, আওয়ামী লীগ"
92,দুর্নীতি দমন কমিশনের মামলায় ঠিকাদার গোলাম কিব...,"দুর্নীতি, আইন, অপরাধ, শিক্ষা, চট্টগ্রাম"
...,...,...
45295,মালয়েশিয়ায় দুই মাসে ১৪ হাজারের বেশি অবৈধ অভিবা...,"আইন-শৃঙ্খলা, আইন, আন্তর্জাতিক, অর্থনীতি, সমাজ,..."
45306,ইহুদিবাদী ইসরায়েল ফিলিস্তিনিদের ইচ্ছাকৃতভাবে অ...,"আন্তর্জাতিক, আইন, যুদ্ধাপরাধ, মানবাধিকার, দুর্..."
45411,গত বছরের ৭ অক্টোবর থেকে ফিলিস্তিনের গাজা উপত্য...,"আন্তর্জাতিক, আইন-শৃঙ্খলা, মানবাধিকার, অপরাধ"
45443,রাশিয়ান ফেডারেশনের কৌশলগত পারমাণবিক বাহিনীতে আ...,"রাজনীতি, আন্তর্জাতিক, সরকারি-নীতি, সামরিক"
45445,পারমাণবিক ওয়ারহেড বহনে সক্ষম একটি সুপারসনিক সা...,"রাজনীতি, আন্তর্জাতিক, সামরিক-নীতি, কূটনীতি"

In [12]:
invalid = set()

for row in bad_rows["labels"]:
    row_labels = [x.strip() for x in row.split(",")]
    for lbl in row_labels:
        if lbl not in allowed:
            invalid.add(lbl)

invalid

{'',
 "'আইন'",
 "'আইন-শৃঙ্খলা'",
 "'আন্তর্জাতিক",
 "'দুর্নীতি'",
 "'নির্বাচন'",
 "'সরকারি-নীতি'",
 "I've reviewed the text and here's a summary of the key points",
 'Okay',
 "['রাজনীতি'",
 'and and and and and and and and and and and',
 "categorized as requested:\n\n**['রাজনীতি'",
 "here's a breakdown of the text",
 'অটোমোটিভ',
 'অটোমোটিভ শিল্প',
 'অন্যান্য',
 'অন্যান্য-',
 'অন্যান্য-খে',
 'অবকাঠামো',
 'অভিবাসন',
 'অর্থ',
 'আইন-',
 'আও',
 'আওম',
 'আওমীল',
 'আওমীলী',
 'আওয়ামীলীগ',
 'আওয়ামী লীগ',
 'আওয়ামীলীগ',
 'আত্মহত্যা',
 'আদালত অবমাননা',
 'আন্দোলন',
 'আবদুস সোবহান',
 'আবদুস সোবহান গোলাপ',
 'আবর',
 'আবরারের হত্যা',
 'আবহাওয়া',
 'আবহাওয়াবিদদের মতে',
 'আবাওমীলীগ',
 'আয়ারল্যান্ড',
 'ইতিহাস',
 'কूटনীতি',
 'কর্মসংস্থান',
 'কারাগারের নিরাপত্তা',
 'কাশ্মীর',
 'কুমিল্লা',
 'কূট',
 'খাদ্য',
 'খুলনা',
 'গণহত্যা',
 'গণহত্যা দিবস',
 'গুজব',
 'চট',
 'চট্টগ্রাম',
 'চলচ্চিত্র',
 'চাকরি',
 'ছাত্র ইউনিয়ন',
 'ছাত্রদল',
 'ছাত্রলীগ',
 'ছাত্রসংগঠন',
 'জনসংখ্যা',
 'জনসংখ্যাসংকট',
 'জমি',
 'জাতীয় নিরাপত্তা',
 'জাম',
 'জামায়',
 'জেলা',
 'টাঙ্গাইল',
 'টেলিযোগাযোগ',
 'ট্রাফিক সমস্যা',
 'ত্রাণ',
 'ত্রাণ ও দুর্যোগ',
 'ত্রাণ ও সমাজকল্যাণ',
 'দারিদ্র্য',
 'দিনাজপুর',
 'দুর্যোগ',
 'দূর্ঘটনা',
 'দূষণ',
 'ধর্মীয় প্রতিষ্ঠান',
 'নাটোর',
 'নারী নির্যাতন',
 'নৌপরিবহন',
 'নৌবাহিনী',
 'পরমাণু',
 'পরিবহন',
 'পরিবহন/ট্রাফিক',
 'পরিবারের সকল সদস্য',
 'পানি সংকট',
 'পাড়া-প্রতিবেশী',
 'পুরস্কার',
 'প্রকৌশল',
 'প্রতিবাদ',
 'প্রতিরক্ষা',
 'প্রতিরক্ষা সহযোগিতা',
 'প্রবাসী কল্যাণ',
 'প্রবাসী কল্যাণ ও বৈদেশিক কর্মসংস্থান মন্ত্রণালয়',
 'প্রবাসী কল্যাণ ও বৈদেশিক কর্মসংস্থান মন্ত্রণালয়',
 'প্রবাসীকল্যাণ ও বৈদেশিক কর্মসংস্থান মন্ত্রণালয়',
 'প্রশাসন',
 'প্রাণী অধিকার',
 'ফ্যা',
 'বন্যা',
 'বরিশাল',
 'বাজেট',
 'বি এন',
 'বিএনপি',
 'বিক্ষোভ',
 'বিচার বিভাগ',
 'বিদ্যুৎ',
 'বিনিয়োগ',
 'বিনিয়োগ',
 'ভবন',
 'ভিসা',
 'ভ্রমণ',
 'মাদক',
 'মাদারীপুর',
 'মানবাধিকার',
 'মানবাধিকার লঙ্ঘন',
 'মানবাধিকার লঙ্ঘনের বিচার',
 'মানবিক বিপর্যয়',
 'মানবিক সংকট',
 'মানবিক সহায়তা',
 'মুক্তিযুদ্ধ',
 'মৃত্যু',
 'যানজট',
 'যানজট/ট্র',
 'যানবাহন',
 'যুদ্ধ',
 'যুদ্ধবিরতির দাবি',
 'যুদ্ধাপরাধ',
 'যোগাযোগ',
 'রাজস্ব',
 'রাস্তা/ট্রাফিক',
 'রাস্তাঘাট',
 'রাস্তাঘাট/পরিবহন',
 'রেমিট্যান্স',
 'রেল',
 'রেলওয়ে',
 'রেলপথ',
 'রেলপথ উন্নয়ন',
 'রোগ-',
 'রোহিঙ্গা',
 'রোহিঙ্গা প্রত্যাবাসন',
 'রোহিঙ্গা সংকট',
 'শিল্প-',
 'শিল্প-কার',
 'শিশুশ্রম',
 'শোক',
 'শ্রম',
 'শ্রম-কারখানা',
 'শ্রমিক অধিকার',
 'শ্রমিক অসন্তোষ',
 'শ্রমিক কর্মচারী',
 'শ্রমিক-কর্মচারী',
 'সংসদের',
 'সতর্কতা',
 'সন্ত্রাসবাদ',
 'সম্মানসূচক নাগরিকত্ব',
 'সরকার',
 'সামরিক',
 'সামরিক আইন',
 'সামরিক উত্তেজনা',
 'সামরিক প্রযুক্তি',
 'সামরিক বাহিনী',
 'সামরিক সহযোগিতা',
 'সামরিক-নীতি',
 'সামরিক-প্রযুক্তিগত সহযোগিতা',
 'সামরিক-বাহিনী',
 'সামরিক-শিল্প-কারখানা',
 'সাহিত্য',
 'সিলেট',
 'সেলিব',
 'স্কুল-আপনারা আপনাদের নিজ নিজ অবস্থান থেকে ছেলে শিশু ও মেয়ে শিশুর মধ্যে যেন',
 'স্থানীয় সংবাদ',
 'স্থানীয় সরকার'}

In [13]:
len(invalid)

175

In [14]:
def clean_label(labels_str):
    lbl_str = [x.strip() for x in labels_str.split(',')]
    clear_lbl = [l for l in lbl_str if l not in invalid]
    return ", ".join(clear_lbl)

In [15]:
df['labels'] = df['labels'].apply(clean_label)

In [16]:
df.head()

,text,labels
0,ইসলামিক ফাউন্ডেশনের নতুন মহাপরিচালক হিসেবে পদা...,"সরকারি-নীতি, ধর্ম, সমাজ"
1,২৭তম বিসিএসে প্রথম মৌখিক পরীক্ষা বাতিলের রায়ের...,"আইন, সরকারি-নীতি, শিক্ষা"
2,রাজধানীর দক্ষিণখান থানায় করা সাইবার নিরাপত্তা ...,"আইন, আইন-শৃঙ্খলা, অপরাধ, রাজনীতি, ঢাকা"
3,বাংলাদেশ জাতীয় ক্রিকেট দলের সাবেক অধিনায়ক ও সা...,"রাজনীতি, অর্থনীতি, ব্যাংকিং, দুর্নীতি, আইন-শৃঙ..."
4,সময়ের হিসেবে ৯ বছর। টাকার হিসেবটা ৮ হাজার কোটি...,"রাজনীতি, দুর্নীতি, অর্থনীতি, বাণিজ্য, সরকারি-ন..."

In [17]:
df.shape

(45451, 2)

In [18]:
df_after = df[df["labels"].apply(lambda lbls: any(l not in allowed for l in lbls))]

In [19]:
df_after.shape

(45446, 2)

In [20]:
bad_rows = df_after[df_after["labels"].apply(find_illegal_str)]
len(bad_rows)

0

In [21]:
df = df_after.copy()

In [22]:
def duplicate_free(lst):
    labels = [x.strip() for x in lst.split(',')]
    seen = set()
    result = []
    for l in labels:
        if l not in seen:
            result.append(l)
            seen.add(l)
    return ', '.join(result)

In [23]:
df['labels'] = df['labels'].apply(duplicate_free)

In [24]:
df.head()

,text,labels
0,ইসলামিক ফাউন্ডেশনের নতুন মহাপরিচালক হিসেবে পদা...,"সরকারি-নীতি, ধর্ম, সমাজ"
1,২৭তম বিসিএসে প্রথম মৌখিক পরীক্ষা বাতিলের রায়ের...,"আইন, সরকারি-নীতি, শিক্ষা"
2,রাজধানীর দক্ষিণখান থানায় করা সাইবার নিরাপত্তা ...,"আইন, আইন-শৃঙ্খলা, অপরাধ, রাজনীতি, ঢাকা"
3,বাংলাদেশ জাতীয় ক্রিকেট দলের সাবেক অধিনায়ক ও সা...,"রাজনীতি, অর্থনীতি, ব্যাংকিং, দুর্নীতি, আইন-শৃঙ..."
4,সময়ের হিসেবে ৯ বছর। টাকার হিসেবটা ৮ হাজার কোটি...,"রাজনীতি, দুর্নীতি, অর্থনীতি, বাণিজ্য, সরকারি-ন..."

In [25]:
df.shape

(45446, 2)

In [26]:
df['text'][10]

'প্রধান উপদেষ্টার প্রেস সেক্রেটারি শফিকুল আলম বলেছেন, ‘প্রধান উপদেষ্টা অধ্যাপক মুহাম্মদ ইউনূসের সঙ্গে যুক্তরাষ্ট্রের ডেমোক্রেটিক পার্টি, রিপাবলিকান পার্টি সবার সঙ্গে খুব ভালো সম্পর্ক আছে। তাদের শীর্ষ নেতাদের সঙ্গে তার ভালো বন্ধুত্ব আছে। আবারও যুক্তরাষ্ট্রের প্রেসিডেন্ট নির্বাচিত হওয়ায় ডোনাল্ড ট্রাম্পকে অধ্যাপক ইউনূস শুভেচ্ছাবার্তা পাঠিয়েছেন। ডোনাল্ড ট্রাম্পের প্রেসিডেন্সিতে বাংলাদেশের সঙ্গে যুক্তরাষ্ট্রের সম্পর্ক আরও গভীর হবে।’ ADVERTISEMENT আজ বুধবার রাজধানীর ফরেন সার্ভিস একাডেমিতে এক সংবাদ সম্মেলনে এসব কথা বলেন তিনি। এ সময় উপ প্রেস সেক্রেটারি আবুল কালাম আজাদ মজুমদার ও অপূর্ব জাহাঙ্গীর উপস্থিত ছিলেন। শফিকুল আলম বলেন, ‘বিবিসি, সিএনএন, নিউইয়র্ক টাইমস জানিয়েছে, ডোনাল্ড ট্রাম্প আবারো আমেরিকার প্রেসিডেন্ট হয়েছেন। আমরা স্বাগত জানিয়েছি। বাংলাদেশের সঙ্গে আমেরিকার আগে থেকেই সুসম্পর্ক রয়েছে। এবার গণবিপ্লবের পর এটা আরো ভিন্নমাত্রা পেয়েছে। কারণ, যুক্তরাষ্ট্র চায় বিশ্বের সকল দেশে গণতন্ত্র বজায় থাকুক। ওরা দেখছে আগের ১৫ বছর বাংলাদেশে যে ডিক্টেটরশিপ ছিল, সেখান থেকে বর্তমান সরকার দেশকে একটি গণতান্ত্রিক পথে নেওয়ার চেষ্টা করছে। এজন্য তারা বাংলাদেশের সঙ্গে কাজ করা আরো বাড়িয়ে দিয়েছে। আমরা আশা করছি, ডোনাল্ড ট্রাম্পের মাধ্যমে বাংলাদেশের সঙ্গে আমেরিকার সম্পর্ক আরো উচ্চ শিখরে যাবে।’ ADVERTISEMENT বাংলাদেশে সংখ্যালঘু নির্যাতন বাড়ছে বলে উদ্বেগ প্রকাশ করে ডোনাল্ড ট্রাম্পের টুইট প্রসঙ্গে এক প্রশ্নের জবাবে প্রেস সেক্রেটারি বলেন, ‘ডোনাল্ড ট্রাম্প যখন টুইট করেছিলেন তখন উনি ছিলেন রিপাবলিকান পার্টির প্রেসিডেন্ট প্রার্থী। উনাকে বিভ্রান্ত করা হয়েছে। এখন যখন উনি প্রেসিডেন্ট হবেন, তখন নিশ্চয়ই দেখবেন প্রকৃত ঘটনাটা কী। এখানে প্রশ্ন হচ্ছে বর্তমান সরকার আসলে কী চাইছে? তারা দেশটাকে একটা গণতান্ত্রিক প্রক্রিয়ায় নিতে চাইছে। ডোনাল্ড ট্রাম্প নিশ্চয়ই চাইবেন সারা পৃথিবীতে গণতন্ত্র ছড়িয়ে পড়ুক। এজন্য আমাদের সরকারের সঙ্গে তাদের সম্পর্ক আরো সুদৃঢ় হবে বলে আমরা মনে করি।’ তিনি বলেন, ‘বাংলাদেশের সংখ্যালঘু নিয়ে অনেক ভুল তথ্য, অপতথ্য আছে। বাংলাদেশের ৯ জন হিন্দুর মৃত্যু নিয়ে যে রিপোর্ট হয়েছে, সেখানে দেখা যাচ্ছে কোনোটি রাজনৈতিক কারণে, কোনোটি ব্যক্তিগত কারণে। ধর্মীয় কোনো সংশ্লিষ্টতা নেই। আমরা গণমাধ্যমের কাছে আবেদন জানাবো দায়িত্বশীলতার সঙ্গে রিপোর্ট করার জন্য। কারণ, আমাদের রিপোর্টগুলো নিয়ে নানা ধরনের ক্যাম্পেইন হয়। যেটা সত্য আমরা চাই সেটা ফুটে উঠুক। অসত্যকে যেন ছড়িয়ে দেওয়া না হয়।’ ADVERTISEMENT সংখ্যালঘুদের মধ্যে উদ্যোগ প্রসঙ্গে এক প্রশ্নের জবাবে শফিকুল আলম বলেন, ‘এই সরকার সকল ধর্মের মানুষের নিরাপত্তা প্রদানে বদ্ধপরিকর। দুর্গাপূজার সময় সংখ্যালঘু নিয়ে অনেক কথা হয়েছিল। কিন্তু দুর্গাপূজা অত্যন্ত শান্তিপূর্ণভাবে অনুষ্ঠিত হয়েছে। বাংলাদেশে প্রথমবারের মতো অ্যাপের মাধ্যমে সবগুলো পূজামণ্ডপ পর্যবেক্ষণ করা হয়েছে।’ শিক্ষাখাত সংস্কারে কমিশন করা হবে কি না এমন প্রশ্নের জবাবে তিনি বলেন, ‘রাষ্ট্র সংস্কারের বড় খাত শিক্ষা। এটা নিয়ে কাজ হবে। তবে কমিশন কবে নাগাদ হবে এ ব্যাপারে এখনো সিদ্ধান্ত হয়নি।’ এ সময় নিষেধাজ্ঞা সত্ত্বেও সাবেক স্পিকার ড. শিরীন শারমিন চৌধুরী ও তার স্বামীর পাসপোর্ট দেওয়ার বিষয়টি খতিয়ে দেখা হচ্ছে বলে তিনি জানান। ADVERTISEMENT যুক্তরাষ্ট্রভিত্তিক বাংলা সংবাদ মাধ্যম ঠিকানায় খালেদ মুহিউদ্দীনের টকশোতে নিষিদ্ধ সংগঠন ছাত্রলীগের সভাপতিকে দাওয়াত দেওয়া প্রসঙ্গে এক প্রশ্নের জবাবে শফিকুল আলম বলেন, ‘তিনি দেশের বাইরে থেকে এ অনুষ্ঠান করছেন। তিনি দায়িত্বশীল সাংবাদিকতা করছেন কি না এই আত্মজিজ্ঞাসা তিনি করবেন বলে আশা করি।’ সংবাদ সম্মেলনে প্রধান উপদেষ্টার বিভিন্ন বৈঠকের বিষয় তুলে ধরে প্রেস সেক্রেটারি বলেন, ‘বুধবার সকালে প্রধান উপদেষ্টার সঙ্গে দেখা করেন শহীদ আবু সাঈদের দুই ভাই। আবু সাঈদের বীরত্বের কথা জাতিসংঘের জেনারেল অ্যাসেম্বলির ভাষণে বলার জন্য তারা প্রধান উপদেষ্টাকে ধন্যবাদ জানাতে এসেছিলেন। একইসঙ্গে তারা আবু সাঈদের নামে একটা ফাউন্ডেশন করতে চান, এজন্য তারা প্রধান উপদেষ্টার সহযোগিতা কামনা করেছেন। আবু সাঈদের নামে একটি মেডিকেল কলেজ ও একটি মডেল মসজিদ করতে চান তারা।’ ADVERTISEMENT এছাড়া বুধবার ইউরোপীয় ইউনিয়নের একটা দল অধ্যাপক ইউনূসের সঙ্গে দেখা করে এই সরকারের প্রতি তাদের পূর্ণ সমর্থন জ্ঞাপন করেছেন। তারা জানিয়েছেন, ইউরোপীয় ইউনিয়নের ভাইস প্রেসিডেন্ট আসছেন জানুয়ারিতে। অনেকগুলো ট্রেড, বিনিয়োগ নিয়ে কথা হবে। তারা দুর্নীতি দমন ও নবায়নযোগ্য জ্বালানিতে শিফট্ করার ক্ষেত্রে আমাদেরকে সহযোগিতা করতে চান। এর বাইরে বুধবার ব্রাজিলের অ্যাম্বাসেডর প্রধান উপদেষ্টার সঙ্গে সাক্ষাৎ করেন জানিয়ে শফিকুল আলম বলেন, ‘তারাও আমাদের সঙ্গে কাজ করতে চায়। প্রধান উপদেষ্টা তাদেরকে জানিয়েছেন, বাংলাদেশ ব্রাজিলের সঙ্গে সম্পর্ক আরও সুদৃঢ় করতে চায়।’ বিডি প্রতিনিধি/জুনাইদ ADVERTISEMENT'

In [27]:
import re

# Pattern 1: remove "ADVERTISEMENT"
# Pattern 2: remove "বিডি প্রতিনিধি/<Bangla name>"
pattern = r"ADVERTISEMENT| বিডি প্রতিনিধি/[ঀ-৿া-ৣ৤-৺]+"

df['text'] = df['text'].str.replace(pattern, "", regex=True).str.strip()

In [28]:
df['text'][10]

'প্রধান উপদেষ্টার প্রেস সেক্রেটারি শফিকুল আলম বলেছেন, ‘প্রধান উপদেষ্টা অধ্যাপক মুহাম্মদ ইউনূসের সঙ্গে যুক্তরাষ্ট্রের ডেমোক্রেটিক পার্টি, রিপাবলিকান পার্টি সবার সঙ্গে খুব ভালো সম্পর্ক আছে। তাদের শীর্ষ নেতাদের সঙ্গে তার ভালো বন্ধুত্ব আছে। আবারও যুক্তরাষ্ট্রের প্রেসিডেন্ট নির্বাচিত হওয়ায় ডোনাল্ড ট্রাম্পকে অধ্যাপক ইউনূস শুভেচ্ছাবার্তা পাঠিয়েছেন। ডোনাল্ড ট্রাম্পের প্রেসিডেন্সিতে বাংলাদেশের সঙ্গে যুক্তরাষ্ট্রের সম্পর্ক আরও গভীর হবে।’  আজ বুধবার রাজধানীর ফরেন সার্ভিস একাডেমিতে এক সংবাদ সম্মেলনে এসব কথা বলেন তিনি। এ সময় উপ প্রেস সেক্রেটারি আবুল কালাম আজাদ মজুমদার ও অপূর্ব জাহাঙ্গীর উপস্থিত ছিলেন। শফিকুল আলম বলেন, ‘বিবিসি, সিএনএন, নিউইয়র্ক টাইমস জানিয়েছে, ডোনাল্ড ট্রাম্প আবারো আমেরিকার প্রেসিডেন্ট হয়েছেন। আমরা স্বাগত জানিয়েছি। বাংলাদেশের সঙ্গে আমেরিকার আগে থেকেই সুসম্পর্ক রয়েছে। এবার গণবিপ্লবের পর এটা আরো ভিন্নমাত্রা পেয়েছে। কারণ, যুক্তরাষ্ট্র চায় বিশ্বের সকল দেশে গণতন্ত্র বজায় থাকুক। ওরা দেখছে আগের ১৫ বছর বাংলাদেশে যে ডিক্টেটরশিপ ছিল, সেখান থেকে বর্তমান সরকার দেশকে একটি গণতান্ত্রিক পথে নেওয়ার চেষ্টা করছে। এজন্য তারা বাংলাদেশের সঙ্গে কাজ করা আরো বাড়িয়ে দিয়েছে। আমরা আশা করছি, ডোনাল্ড ট্রাম্পের মাধ্যমে বাংলাদেশের সঙ্গে আমেরিকার সম্পর্ক আরো উচ্চ শিখরে যাবে।’  বাংলাদেশে সংখ্যালঘু নির্যাতন বাড়ছে বলে উদ্বেগ প্রকাশ করে ডোনাল্ড ট্রাম্পের টুইট প্রসঙ্গে এক প্রশ্নের জবাবে প্রেস সেক্রেটারি বলেন, ‘ডোনাল্ড ট্রাম্প যখন টুইট করেছিলেন তখন উনি ছিলেন রিপাবলিকান পার্টির প্রেসিডেন্ট প্রার্থী। উনাকে বিভ্রান্ত করা হয়েছে। এখন যখন উনি প্রেসিডেন্ট হবেন, তখন নিশ্চয়ই দেখবেন প্রকৃত ঘটনাটা কী। এখানে প্রশ্ন হচ্ছে বর্তমান সরকার আসলে কী চাইছে? তারা দেশটাকে একটা গণতান্ত্রিক প্রক্রিয়ায় নিতে চাইছে। ডোনাল্ড ট্রাম্প নিশ্চয়ই চাইবেন সারা পৃথিবীতে গণতন্ত্র ছড়িয়ে পড়ুক। এজন্য আমাদের সরকারের সঙ্গে তাদের সম্পর্ক আরো সুদৃঢ় হবে বলে আমরা মনে করি।’ তিনি বলেন, ‘বাংলাদেশের সংখ্যালঘু নিয়ে অনেক ভুল তথ্য, অপতথ্য আছে। বাংলাদেশের ৯ জন হিন্দুর মৃত্যু নিয়ে যে রিপোর্ট হয়েছে, সেখানে দেখা যাচ্ছে কোনোটি রাজনৈতিক কারণে, কোনোটি ব্যক্তিগত কারণে। ধর্মীয় কোনো সংশ্লিষ্টতা নেই। আমরা গণমাধ্যমের কাছে আবেদন জানাবো দায়িত্বশীলতার সঙ্গে রিপোর্ট করার জন্য। কারণ, আমাদের রিপোর্টগুলো নিয়ে নানা ধরনের ক্যাম্পেইন হয়। যেটা সত্য আমরা চাই সেটা ফুটে উঠুক। অসত্যকে যেন ছড়িয়ে দেওয়া না হয়।’  সংখ্যালঘুদের মধ্যে উদ্যোগ প্রসঙ্গে এক প্রশ্নের জবাবে শফিকুল আলম বলেন, ‘এই সরকার সকল ধর্মের মানুষের নিরাপত্তা প্রদানে বদ্ধপরিকর। দুর্গাপূজার সময় সংখ্যালঘু নিয়ে অনেক কথা হয়েছিল। কিন্তু দুর্গাপূজা অত্যন্ত শান্তিপূর্ণভাবে অনুষ্ঠিত হয়েছে। বাংলাদেশে প্রথমবারের মতো অ্যাপের মাধ্যমে সবগুলো পূজামণ্ডপ পর্যবেক্ষণ করা হয়েছে।’ শিক্ষাখাত সংস্কারে কমিশন করা হবে কি না এমন প্রশ্নের জবাবে তিনি বলেন, ‘রাষ্ট্র সংস্কারের বড় খাত শিক্ষা। এটা নিয়ে কাজ হবে। তবে কমিশন কবে নাগাদ হবে এ ব্যাপারে এখনো সিদ্ধান্ত হয়নি।’ এ সময় নিষেধাজ্ঞা সত্ত্বেও সাবেক স্পিকার ড. শিরীন শারমিন চৌধুরী ও তার স্বামীর পাসপোর্ট দেওয়ার বিষয়টি খতিয়ে দেখা হচ্ছে বলে তিনি জানান।  যুক্তরাষ্ট্রভিত্তিক বাংলা সংবাদ মাধ্যম ঠিকানায় খালেদ মুহিউদ্দীনের টকশোতে নিষিদ্ধ সংগঠন ছাত্রলীগের সভাপতিকে দাওয়াত দেওয়া প্রসঙ্গে এক প্রশ্নের জবাবে শফিকুল আলম বলেন, ‘তিনি দেশের বাইরে থেকে এ অনুষ্ঠান করছেন। তিনি দায়িত্বশীল সাংবাদিকতা করছেন কি না এই আত্মজিজ্ঞাসা তিনি করবেন বলে আশা করি।’ সংবাদ সম্মেলনে প্রধান উপদেষ্টার বিভিন্ন বৈঠকের বিষয় তুলে ধরে প্রেস সেক্রেটারি বলেন, ‘বুধবার সকালে প্রধান উপদেষ্টার সঙ্গে দেখা করেন শহীদ আবু সাঈদের দুই ভাই। আবু সাঈদের বীরত্বের কথা জাতিসংঘের জেনারেল অ্যাসেম্বলির ভাষণে বলার জন্য তারা প্রধান উপদেষ্টাকে ধন্যবাদ জানাতে এসেছিলেন। একইসঙ্গে তারা আবু সাঈদের নামে একটা ফাউন্ডেশন করতে চান, এজন্য তারা প্রধান উপদেষ্টার সহযোগিতা কামনা করেছেন। আবু সাঈদের নামে একটি মেডিকেল কলেজ ও একটি মডেল মসজিদ করতে চান তারা।’  এছাড়া বুধবার ইউরোপীয় ইউনিয়নের একটা দল অধ্যাপক ইউনূসের সঙ্গে দেখা করে এই সরকারের প্রতি তাদের পূর্ণ সমর্থন জ্ঞাপন করেছেন। তারা জানিয়েছেন, ইউরোপীয় ইউনিয়নের ভাইস প্রেসিডেন্ট আসছেন জানুয়ারিতে। অনেকগুলো ট্রেড, বিনিয়োগ নিয়ে কথা হবে। তারা দুর্নীতি দমন ও নবায়নযোগ্য জ্বালানিতে শিফট্ করার ক্ষেত্রে আমাদেরকে সহযোগিতা করতে চান। এর বাইরে বুধবার ব্রাজিলের অ্যাম্বাসেডর প্রধান উপদেষ্টার সঙ্গে সাক্ষাৎ করেন জানিয়ে শফিকুল আলম বলেন, ‘তারাও আমাদের সঙ্গে কাজ করতে চায়। প্রধান উপদেষ্টা তাদেরকে জানিয়েছেন, বাংলাদেশ ব্রাজিলের সঙ্গে সম্পর্ক আরও সুদৃঢ় করতে চায়।’'

In [29]:
df['text'][1000]

'স্থানীয় সরকার বিভাগের সচিব আবু হেনা মোরশেদ জামানকে বিশেষ ভারপ্রাপ্ত কর্মকর্তা (ওএসডি) করা হয়েছে।  আজ রবিবার তাকে ওএসডি করে জনপ্রশাসন মন্ত্রণালয় থেকে প্রজ্ঞাপন জারি করা হয়েছে। এদিকে, শিল্প মন্ত্রণালয়ের অতিরিক্ত সচিব এস এম আলমকে ওএসডি করা হয়েছে। ওএসডি অতিরিক্ত সচিব মো. সাইদুর রহমান খানকে মন্ত্রিপরিষদ বিভাগে পদায়ন করা হয়েছে। জনপ্রশাসন মন্ত্রণালয়ে সংযুক্ত অতিরিক্ত সচিব মো. আল-আমিন সরকারকে বাস্তবায়ন, পরিবীক্ষণ ও মূল্যায়ন বিভাগের (আইএমইডি) বদলি করা হয়েছে। বিডি প্রতিদিন/জুনাইদ'

In [30]:
pat = r"\s*বিডি\s(?:প্রতিনিধি|প্রতিদিন)/[ঀ-৿া-ৣ৤-৺'\. ]+"
df['text'] = df['text'].str.replace(pat, "", regex=True).str.strip()

In [31]:
df['text'][1000]

'স্থানীয় সরকার বিভাগের সচিব আবু হেনা মোরশেদ জামানকে বিশেষ ভারপ্রাপ্ত কর্মকর্তা (ওএসডি) করা হয়েছে।  আজ রবিবার তাকে ওএসডি করে জনপ্রশাসন মন্ত্রণালয় থেকে প্রজ্ঞাপন জারি করা হয়েছে। এদিকে, শিল্প মন্ত্রণালয়ের অতিরিক্ত সচিব এস এম আলমকে ওএসডি করা হয়েছে। ওএসডি অতিরিক্ত সচিব মো. সাইদুর রহমান খানকে মন্ত্রিপরিষদ বিভাগে পদায়ন করা হয়েছে। জনপ্রশাসন মন্ত্রণালয়ে সংযুক্ত অতিরিক্ত সচিব মো. আল-আমিন সরকারকে বাস্তবায়ন, পরিবীক্ষণ ও মূল্যায়ন বিভাগের (আইএমইডি) বদলি করা হয়েছে।'

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45446 entries, 0 to 45460
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    45446 non-null  object
 1   labels  45446 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [33]:
df = df.reset_index(drop=True)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45446 entries, 0 to 45445
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    45446 non-null  object
 1   labels  45446 non-null  object
dtypes: object(2)
memory usage: 710.2+ KB

In [35]:
df.to_csv('final_annotated_dataset.csv', index = False)